@php
echo '<?php'
@endphp

/**
 * DO NOT EDIT!!!
 * Autogenerated CRUD routes for module {{\Illuminate\Support\Str::ucfirst($module)}}
 * If custom routes are needed for this module
 * please define them in {{\Illuminate\Support\Str::ucfirst($module)}}/Routes/custom/ directory, they will be automatically loaded
 */

use Illuminate\Support\Facades\Route;

@foreach($models as $model)
/**
 * CRUD routes for model {{$model['class']}}
 */
Route::group(["prefix" => "{{$routePrefix}}{{$model['name']}}"], function ($router) {
    $router->get('/', ['uses' => '\{{$model['controller']}}@readMore', 'model' => '{{$model['name']}}', 'namespace' => '{{$namespace}}']);
    $router->get('/{id}', ['uses' => '\{{$model['controller']}}@readOne', 'model' => '{{$model['name']}}', 'namespace' => '{{$namespace}}']);
    $router->post('/', ['uses' => '\{{$model['controller']}}@create', 'model' => '{{$model['name']}}', 'namespace' => '{{$namespace}}']);
    $router->put('/{id}', ['uses' => '\{{$model['controller']}}@update', 'model' => '{{$model['name']}}', 'namespace' => '{{$namespace}}']);
    $router->delete('/{id}', ['uses' => '\{{$model['controller']}}@delete', 'model' => '{{$model['name']}}', 'namespace' => '{{$namespace}}']);
    $router->put('/{id}/relation/{relationField}', ['uses' => '\{{$model['controller']}}@addRelation', 'model' => '{{$model['name']}}', 'namespace' => '{{$namespace}}']);
    $router->delete('/{id}/relation/{relationField}/{relationId}', ['uses' => '\{{$model['controller']}}@removeRelation', 'model' => '{{$model['name']}}', 'namespace' => '{{$namespace}}']);
});
@endforeach